"use client";

import { useEffect, useState, type FormEvent } from "react";
import { Activity, CalendarDays, Check, ChevronRight, HeartPulse, History, Plus, Ruler, Scale, TrendingUp, X } from "lucide-react";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle } from "@nomos/ui";
import type { HevyWorkout } from "@/lib/hevy-types";

type ProgressEntry = { date: string; weight: string; note: string; wellbeing?: string };
type Injury = { name: string; severity: "Low" | "Moderate"; trend: string; latest: string; history: string[] };

const weightHistory = [
  { date: "Jun 03", value: 67.4 }, { date: "Jun 17", value: 68.1 }, { date: "Jul 01", value: 68.9 },
  { date: "Jul 15", value: 69.4 }, { date: "Jul 29", value: 70.1 }, { date: "Aug 12", value: 70.6 }, { date: "Aug 26", value: 71.0 },
];
const measurements = [{ label: "Waist", value: "84 cm", change: "−4 cm" }, { label: "Chest", value: "103 cm", change: "+2 cm" }, { label: "Arms", value: "38 cm", change: "+1.5 cm" }, { label: "Thighs", value: "61 cm", change: "+1 cm" }];
const initialInjuries: Injury[] = [{ name: "Left shoulder", severity: "Low", trend: "Improving", latest: "Mild tightness after pressing · 4 days ago", history: ["Sep 01 · Mild tightness after pressing", "Aug 25 · Reduced discomfort, full range of motion", "Aug 18 · Noticeable discomfort on overhead press"] }];
const initialEntries: ProgressEntry[] = [{ date: "Sep 01, 2026", weight: "71.0 kg", note: "Training felt strong this week.", wellbeing: "Sleep has been consistent." }, { date: "Aug 18, 2026", weight: "70.6 kg", note: "Added reps to bench and squat." }, { date: "Aug 04, 2026", weight: "69.8 kg", note: "Good energy across all sessions.", wellbeing: "7/10 recovery" }];
function OverallTrainingChart({ workouts, loading }: { workouts: HevyWorkout[]; loading: boolean }) {
  const sorted = [...workouts].sort((a, b) => new Date(a.start_time).getTime() - new Date(b.start_time).getTime());
  const points = sorted.slice(-12).map((workout) => ({
    date: new Date(workout.start_time),
    title: workout.title,
    volume: workout.exercises.reduce((total, exercise) => total + exercise.sets.reduce((sum, set) => sum + (set.weight_kg ?? 0) * (set.reps ?? 0), 0), 0),
    sets: workout.exercises.reduce((total, exercise) => total + exercise.sets.filter((set) => set.type !== "warmup").length, 0),
  })).filter((point) => !Number.isNaN(point.date.getTime()));
  const max = Math.max(...points.map((point) => point.volume), 1);
  const x = (index: number) => points.length > 1 ? 12 + index * (288 / (points.length - 1)) : 150;
  const y = (volume: number) => 112 - (volume / max) * 92;
  const injuryStart = new Date("2026-08-18").getTime();
  const injuryEnd = new Date("2026-09-01").getTime();
  return <Card><CardHeader><div><CardTitle>Total training progress</CardTitle><p className="mt-1 text-sm text-[var(--muted-foreground)]">Volume across every Hevy session</p></div></CardHeader><CardContent>{loading ? <div className="grid h-56 place-items-center text-sm text-[var(--muted-foreground)]">Loading your Hevy history…</div> : !points.length ? <div className="grid h-56 place-items-center text-center text-sm text-[var(--muted-foreground)]">No completed Hevy sessions found yet.</div> : <><div className="relative"><svg viewBox="0 0 300 132" className="h-56 w-full overflow-visible" role="img" aria-label="Total training volume over time"><line x1="12" y1="112" x2="300" y2="112" stroke="currentColor" className="text-white/10"/><polyline points={points.map((point, index) => `${x(index)},${y(point.volume)}`).join(" ")} fill="none" stroke="#f0abfc" strokeOpacity=".16" strokeWidth="10" strokeLinecap="round" strokeLinejoin="round"/>{points.slice(1).map((point, index) => { const affected = point.date.getTime() >= injuryStart && point.date.getTime() <= injuryEnd; return <line key={`${point.date.toISOString()}-segment`} x1={x(index)} y1={y(points[index].volume)} x2={x(index + 1)} y2={y(point.volume)} stroke={affected ? "#fb7185" : "#86efac"} strokeWidth="3" strokeLinecap="round"/>; })}{points.map((point, index) => { const affected = point.date.getTime() >= injuryStart && point.date.getTime() <= injuryEnd; return <circle key={point.date.toISOString()} cx={x(index)} cy={y(point.volume)} r="4" fill={affected ? "#fb7185" : "#211a30"} stroke={affected ? "#fb7185" : "#86efac"} strokeWidth="2"><title>{`${point.date.toLocaleDateString(undefined, { day: "numeric", month: "short" })} · ${point.title} · ${Math.round(point.volume).toLocaleString()} kg volume · ${point.sets} sets${affected ? " · injury period" : ""}`}</title></circle>; })}</svg><div className="mt-1 flex justify-between text-[10px] text-[var(--muted-foreground)]"><span>{points[0].date.toLocaleDateString(undefined, { day: "numeric", month: "short" })}</span><span>{points[points.length - 1].date.toLocaleDateString(undefined, { day: "numeric", month: "short" })}</span></div></div><div className="mt-4 flex flex-wrap gap-4 text-xs text-[var(--muted-foreground)]"><span className="inline-flex items-center gap-2"><i className="size-2 rounded-full bg-emerald-300"/>Normal training</span><span className="inline-flex items-center gap-2"><i className="size-2 rounded-full bg-rose-400"/>Logged injury period</span></div></>}</CardContent></Card>;
}

function WeightChart() {
  const y = (value: number) => 102 - ((value - 66) / 15) * 82;
  const points = weightHistory.map((item, index) => `${index * 52 + 8},${y(item.value)}`).join(" ");
  const goalY = y(80);
  return <div className="mt-5"><div className="flex items-end justify-between text-xs text-[var(--muted-foreground)]"><span>80 kg goal</span><span>71.0 kg now</span></div><svg viewBox="0 0 320 110" className="mt-2 h-32 w-full overflow-visible" role="img" aria-label="Weight trending up from 67.4 to 71 kilograms toward an 80 kilogram goal"><defs><linearGradient id="weight-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#f0abfc" stopOpacity=".28"/><stop offset="1" stopColor="#f0abfc" stopOpacity="0"/></linearGradient></defs><path d={`M8,${y(weightHistory[0].value)} L${points.split(" ").slice(1).join(" L")} L320,110 L8,110 Z`} fill="url(#weight-fill)"/><line x1="8" y1={goalY} x2="320" y2={goalY} stroke="#f0abfc" strokeOpacity=".45" strokeDasharray="4 5"/><text x="316" y={goalY - 5} textAnchor="end" fill="#f0abfc" fontSize="8">80 kg</text><polyline points={points} fill="none" stroke="#f0abfc" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>{weightHistory.map((item, index) => <circle key={item.date} cx={index * 52 + 8} cy={y(item.value)} r="3.5" fill="#211a30" stroke="#f0abfc" strokeWidth="2"/>)}<line x1="8" y1="110" x2="320" y2="110" stroke="currentColor" className="text-white/10"/></svg><div className="flex justify-between text-[10px] text-[var(--muted-foreground)]"><span>Jun 03</span><span>Aug 26</span></div></div>;
}

function ProgressDialog({ onClose, onSave }: { onClose: () => void; onSave: (entry: ProgressEntry) => void }) {
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    onSave({ date: "Sep 01, 2026", weight: `${form.get("weight") || "—"} kg`, note: String(form.get("note") || "Progress update"), wellbeing: String(form.get("wellbeing") || "") || undefined });
  }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 p-0 backdrop-blur-sm sm:items-center sm:p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div role="dialog" aria-modal="true" aria-labelledby="log-progress-title" className="max-h-[92dvh] w-full max-w-xl overflow-y-auto rounded-t-3xl border border-[var(--border)] bg-[var(--card)] p-5 shadow-2xl sm:rounded-3xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">PROGRESS LOG</p><h2 id="log-progress-title" className="mt-1 text-2xl font-semibold">Log update</h2></div><button type="button" onClick={onClose} className="grid size-11 place-items-center rounded-xl text-[var(--muted-foreground)] hover:bg-[var(--muted)]" aria-label="Close log update"><X className="size-5"/></button></div><form onSubmit={submit} className="mt-6 space-y-5"><label className="block"><span className="mb-2 block text-sm font-medium">Weight <span className="text-[var(--muted-foreground)]">(kg)</span></span><input name="weight" type="number" step="0.1" placeholder="82.1" className="field-input h-11"/></label><div><p className="mb-2 text-sm font-medium">Body measurements <span className="font-normal text-[var(--muted-foreground)]">(optional)</span></p><div className="grid grid-cols-2 gap-3"><input name="waist" placeholder="Waist · cm" className="field-input h-11"/><input name="chest" placeholder="Chest · cm" className="field-input h-11"/><input name="arms" placeholder="Arms · cm" className="field-input h-11"/><input name="thighs" placeholder="Thighs · cm" className="field-input h-11"/></div></div><label className="block"><span className="mb-2 block text-sm font-medium">Injury or pain update <span className="font-normal text-[var(--muted-foreground)]">(optional)</span></span><textarea name="injury" rows={2} placeholder="Anything to keep an eye on?" className="field-input min-h-20 resize-y py-3"/></label><label className="block"><span className="mb-2 block text-sm font-medium">General note</span><textarea name="note" rows={3} placeholder="How did training and nutrition feel?" className="field-input min-h-24 resize-y py-3"/></label><label className="block"><span className="mb-2 block text-sm font-medium">Wellbeing and recovery <span className="font-normal text-[var(--muted-foreground)]">(optional)</span></span><textarea name="wellbeing" rows={2} placeholder="Sleep, stress, energy, soreness…" className="field-input min-h-20 resize-y py-3"/></label><div className="flex flex-col-reverse gap-2 pt-1 sm:flex-row sm:justify-end"><Button type="button" variant="outline" className="min-h-11" onClick={onClose}>Cancel</Button><Button type="submit" className="min-h-11"><Check/>Save update</Button></div></form></div></div>;
}

function HistoryDrawer({ entries, onClose }: { entries: ProgressEntry[]; onClose: () => void }) {
  return <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside role="dialog" aria-modal="true" aria-labelledby="history-title" className="ml-auto flex h-full w-full max-w-lg flex-col border-l border-[var(--border)] bg-[var(--card)] shadow-2xl"><div className="flex items-center justify-between border-b border-[var(--border)] p-5"><div><p className="eyebrow">PROGRESS</p><h2 id="history-title" className="mt-1 text-2xl font-semibold">History</h2></div><button type="button" onClick={onClose} className="grid size-11 place-items-center rounded-xl text-[var(--muted-foreground)] hover:bg-[var(--muted)]" aria-label="Close history"><X className="size-5"/></button></div><div className="flex-1 space-y-6 overflow-y-auto p-5">{entries.map((entry, index) => <div key={`${entry.date}-${index}`} className="relative pl-7"><span className="absolute left-0 top-1.5 grid size-4 place-items-center rounded-full border-2 border-fuchsia-300 bg-[var(--card)]"><span className="size-1.5 rounded-full bg-fuchsia-300"/></span>{index < entries.length - 1 && <span className="absolute bottom-[-1.5rem] left-[7px] top-5 w-px bg-[var(--border)]"/>}<p className="text-xs font-semibold uppercase tracking-[.1em] text-[var(--muted-foreground)]">{entry.date}</p><p className="mt-2 text-lg font-semibold">{entry.weight}</p><p className="mt-1 text-sm leading-6 text-[var(--muted-foreground)]">{entry.note}</p>{entry.wellbeing && <p className="mt-2 text-xs text-fuchsia-200/80">{entry.wellbeing}</p>}</div>)}</div></aside></div>;
}

function AICoachCard({ workouts, loading }: { workouts: HevyWorkout[]; loading: boolean }) {
  const sessionSummary = loading ? "Checking Hevy…" : workouts.length ? `${workouts.length} sessions logged` : "No Hevy sessions yet";
  return <Card className="border-[var(--border)] bg-[var(--card)]"><CardContent className="p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="eyebrow">AI COACH</p><span className="rounded-full bg-emerald-300/15 px-2 py-1 text-[10px] font-semibold text-emerald-200">On track</span></div><p className="mt-2 text-base font-semibold">{loading ? "Reviewing your training history…" : `${workouts.length} sessions logged — consistency is a strength.`}</p><p className="mt-1 max-w-2xl text-sm leading-6 text-[var(--muted-foreground)]">Left shoulder: improving. Keep pressing pain-free and compare this week’s total volume before adding load.</p></div><div className="grid shrink-0 gap-2 sm:grid-cols-2 md:w-[22rem]"><div className="rounded-xl border border-emerald-300/15 bg-emerald-300/[.07] px-3 py-2.5"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-emerald-200/70">Keep doing</p><p className="mt-1 text-sm font-medium text-emerald-100">Train consistently</p></div><div className="rounded-xl border border-amber-300/15 bg-amber-300/[.07] px-3 py-2.5"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-amber-200/70">Next check</p><p className="mt-1 text-sm font-medium text-amber-100">Shoulder + volume</p></div></div></div></CardContent></Card>;
}

export function ProgressPage() {
  const [logOpen, setLogOpen] = useState(false);
  const [historyOpen, setHistoryOpen] = useState(false);
  const [entries, setEntries] = useState(initialEntries);
  const [selectedInjury, setSelectedInjury] = useState<Injury | null>(null);
  const [workouts, setWorkouts] = useState<HevyWorkout[]>([]);
  const [workoutsLoading, setWorkoutsLoading] = useState(true);
  useEffect(() => {
    let active = true;
    fetch("/api/hevy/workouts?history=true", { cache: "no-store" }).then(async (response) => {
      const data = await response.json() as { workouts?: HevyWorkout[] };
      if (!response.ok) throw new Error("Unable to load Hevy history");
      if (active) setWorkouts(Array.isArray(data.workouts) ? data.workouts : []);
    }).catch(() => { if (active) setWorkouts([]); }).finally(() => { if (active) setWorkoutsLoading(false); });
    return () => { active = false; };
  }, []);
  const currentWeight = weightHistory[weightHistory.length - 1].value;
  const remaining = (80 - currentWeight).toFixed(1);
  const lastHevyWorkout = [...workouts].sort((a, b) => new Date(b.start_time).getTime() - new Date(a.start_time).getTime())[0];
  return <div className="space-y-6">
    <section className="overflow-hidden rounded-3xl border border-[#3d3158] bg-[radial-gradient(circle_at_82%_10%,rgba(240,171,252,.18),transparent_34%),linear-gradient(135deg,#211a30,#15121d)] p-6 md:p-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">PROGRESS</p><h2 className="mt-2 max-w-2xl text-3xl font-semibold tracking-[-.045em] md:text-5xl">Closer to <span className="text-fuchsia-200">80 kg.</span><br/><span className="text-[#a99fba]">Stronger every week.</span></h2><p className="mt-4 max-w-xl text-sm leading-6 text-[#aaa3b5]">Your physique, strength, and recovery at a glance.</p></div><div className="flex flex-col gap-2 sm:flex-row"><Button onClick={() => setHistoryOpen(true)} variant="outline" className="min-h-11 border-white/15 bg-white/[.04] text-white hover:bg-white/10"><History/>History</Button><Button onClick={() => setLogOpen(true)} className="min-h-11"><Plus/>Log update</Button></div></div></section>
    <AICoachCard workouts={workouts} loading={workoutsLoading}/>

    <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>Weight trend</CardTitle><p className="mt-1 text-sm text-[var(--muted-foreground)]">{remaining} kg to go · 80 kg target line</p></div><span className="grid size-10 place-items-center rounded-xl bg-fuchsia-300/15 text-fuchsia-200"><Scale className="size-5"/></span></div></CardHeader><CardContent><div className="flex items-end justify-between gap-4"><div><p className="text-4xl font-semibold tracking-[-.05em]">{currentWeight} <span className="text-base font-normal text-[var(--muted-foreground)]">kg</span></p><p className="mt-1 text-sm text-emerald-300">+3.6 kg since June</p></div><div className="text-right"><p className="text-xs uppercase tracking-[.1em] text-[var(--muted-foreground)]">Target</p><p className="mt-1 text-xl font-semibold">80 kg</p></div></div><WeightChart/></CardContent></Card><Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>Training snapshot</CardTitle><p className="mt-1 text-sm text-[var(--muted-foreground)]">From your Hevy history</p></div><TrendingUp className="size-5 text-emerald-300"/></div></CardHeader><CardContent className="space-y-4"><div className="flex items-center justify-between border-b border-[var(--border)] pb-4"><span className="text-sm text-[var(--muted-foreground)]">Sessions logged</span><strong>{workoutsLoading ? "—" : workouts.length}</strong></div><div className="flex items-center justify-between border-b border-[var(--border)] pb-4"><span className="text-sm text-[var(--muted-foreground)]">Latest session</span><strong className="max-w-[9rem] truncate text-right">{workoutsLoading ? "—" : lastHevyWorkout?.title || "—"}</strong></div><div className="flex items-center justify-between"><span className="text-sm text-[var(--muted-foreground)]">Latest date</span><strong>{workoutsLoading || !lastHevyWorkout ? "—" : new Date(lastHevyWorkout.start_time).toLocaleDateString(undefined, { day: "numeric", month: "short" })}</strong></div></CardContent></Card></div>

    <div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>Body</CardTitle><p className="mt-1 text-sm text-[var(--muted-foreground)]">Latest measurements</p></div><Ruler className="size-5 text-[var(--muted-foreground)]"/></div></CardHeader><CardContent><div className="grid grid-cols-2 gap-x-6 gap-y-5 sm:grid-cols-4">{measurements.map((item) => <div key={item.label}><p className="text-xs uppercase tracking-[.1em] text-[var(--muted-foreground)]">{item.label}</p><p className="mt-2 text-xl font-semibold">{item.value}</p><p className="mt-1 text-xs text-emerald-300">{item.change}</p></div>)}</div><div className="mt-6 grid h-20 grid-cols-12 items-end gap-1.5" aria-label="Body measurement trend"><div className="h-7 rounded-t bg-fuchsia-300/30"/><div className="h-9 rounded-t bg-fuchsia-300/35"/><div className="h-8 rounded-t bg-fuchsia-300/40"/><div className="h-11 rounded-t bg-fuchsia-300/45"/><div className="h-12 rounded-t bg-fuchsia-300/50"/><div className="h-14 rounded-t bg-fuchsia-300/55"/><div className="h-16 rounded-t bg-fuchsia-300/60"/><div className="h-[4.5rem] rounded-t bg-fuchsia-300/65"/><div className="h-[4.75rem] rounded-t bg-fuchsia-300/70"/><div className="h-20 rounded-t bg-fuchsia-300/75"/><div className="h-[4.9rem] rounded-t bg-fuchsia-300/80"/><div className="h-[5.1rem] rounded-t bg-fuchsia-300"/></div></CardContent></Card><OverallTrainingChart workouts={workouts} loading={workoutsLoading}/></div>

    <div className="grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>Muscle development</CardTitle><p className="mt-1 text-sm text-[var(--muted-foreground)]">Mock visual status</p></div><Activity className="size-5 text-[var(--muted-foreground)]"/></div></CardHeader><CardContent><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#0d0b12] p-3"><img src="/body.png" alt="Front muscle development mock diagram" className="mx-auto h-64 w-full object-contain"/><p className="mt-2 text-center text-xs font-medium text-[var(--muted-foreground)]">Front</p></div><div className="rounded-2xl bg-[#0d0b12] p-3"><img src="/body.png" alt="Back muscle development mock diagram" className="mx-auto h-64 w-full scale-x-[-1] object-contain"/><p className="mt-2 text-center text-xs font-medium text-[var(--muted-foreground)]">Back · mock</p></div></div><div className="mt-4 flex flex-wrap gap-2"><Badge className="bg-emerald-300/15 text-emerald-200">Growing · legs</Badge><Badge className="bg-sky-300/15 text-sky-200">Steady · chest</Badge><Badge className="bg-amber-300/15 text-amber-200">Focus · shoulders</Badge></div></CardContent></Card><div className="space-y-5"><Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>Injuries & pain</CardTitle><p className="mt-1 text-sm text-[var(--muted-foreground)]">Tap an injury for its history</p></div><HeartPulse className="size-5 text-rose-300"/></div></CardHeader><CardContent className="space-y-2">{initialInjuries.map((injury) => <button key={injury.name} type="button" onClick={() => setSelectedInjury(injury)} className="flex min-h-16 w-full items-center gap-3 rounded-2xl border border-[var(--border)] p-3 text-left transition-colors hover:bg-[var(--muted)]"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-amber-300/15 text-amber-200"><HeartPulse className="size-4"/></span><span className="min-w-0 flex-1"><span className="block font-medium">{injury.name}</span><span className="mt-1 block truncate text-xs text-[var(--muted-foreground)]">{injury.latest}</span></span><span className="shrink-0 text-right"><span className="block text-xs text-amber-200">{injury.severity}</span><span className="mt-1 block text-[10px] text-emerald-300">{injury.trend}</span></span><ChevronRight className="size-4 shrink-0 text-[var(--muted-foreground)]"/></button>)}</CardContent></Card></div></div>

    {logOpen && <ProgressDialog onClose={() => setLogOpen(false)} onSave={(entry) => { setEntries((current) => [entry, ...current]); setLogOpen(false); }}/>} {historyOpen && <HistoryDrawer entries={entries} onClose={() => setHistoryOpen(false)}/>} {selectedInjury && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 p-0 backdrop-blur-sm sm:items-center sm:p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelectedInjury(null); }}><div role="dialog" aria-modal="true" aria-labelledby="injury-title" className="w-full max-w-lg rounded-t-3xl border border-[var(--border)] bg-[var(--card)] p-5 sm:rounded-3xl sm:p-6"><div className="flex items-start justify-between"><div><p className="eyebrow">INJURY HISTORY</p><h2 id="injury-title" className="mt-1 text-2xl font-semibold">{selectedInjury.name}</h2></div><button type="button" onClick={() => setSelectedInjury(null)} className="grid size-11 place-items-center rounded-xl text-[var(--muted-foreground)] hover:bg-[var(--muted)]" aria-label="Close injury history"><X className="size-5"/></button></div><div className="mt-5 flex flex-wrap gap-2"><Badge className="bg-amber-300/15 text-amber-200">{selectedInjury.severity} severity</Badge><Badge className="bg-emerald-300/15 text-emerald-200">{selectedInjury.trend}</Badge></div><div className="mt-6 space-y-4">{selectedInjury.history.map((item) => <div key={item} className="flex gap-3 border-b border-[var(--border)] pb-4 text-sm last:border-0"><CalendarDays className="mt-0.5 size-4 shrink-0 text-[var(--muted-foreground)]"/><span>{item}</span></div>)}</div></div></div>}
  </div>;
}
