"use client";
import * as React from "react";
import * as AvatarPrimitive from "@radix-ui/react-avatar";
import * as DropdownPrimitive from "@radix-ui/react-dropdown-menu";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "./utils";
export { BarChart3, CircleAlert, FileText, FormInput, LayoutGrid, MessageSquare, PanelRight, Sparkles } from "lucide-react";

const buttonVariants = cva("inline-flex min-h-10 cursor-pointer items-center justify-center gap-2 rounded-lg px-4 text-sm font-medium outline-none transition-all active:translate-y-px disabled:pointer-events-none disabled:opacity-50 focus-visible:ring-3 focus-visible:ring-[color-mix(in_srgb,var(--ring)_35%,transparent)] [&_svg]:size-4",{variants:{variant:{default:"bg-[var(--primary)] text-[var(--primary-foreground)] hover:bg-[color-mix(in_srgb,var(--primary)_82%,white)]",outline:"border border-[var(--border)] bg-[var(--background)] text-[var(--foreground)] shadow-sm hover:bg-[var(--muted)] aria-expanded:bg-[var(--accent)] dark:bg-[color-mix(in_srgb,var(--card)_70%,transparent)] dark:hover:bg-[var(--muted)]",ghost:"text-[var(--foreground)] hover:bg-[var(--muted)] aria-expanded:bg-[var(--accent)] dark:hover:bg-[color-mix(in_srgb,var(--muted)_70%,transparent)]"},size:{default:"h-10",sm:"h-9 min-h-9 px-3",icon:"size-11 min-h-11 px-0"}},defaultVariants:{variant:"default",size:"default"}});
export function Button({className,variant,size,asChild=false,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&VariantProps<typeof buttonVariants>&{asChild?:boolean}){const Comp=asChild?Slot:"button";return <Comp className={cn(buttonVariants({variant,size}),className)} {...props}/>}
export function Card({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn("rounded-[var(--radius)] border bg-[var(--card)] text-[var(--card-foreground)] shadow-[0_1px_2px_rgba(20,35,26,.04)]",className)} {...props}/>}
export function CardHeader({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn("flex flex-col gap-1.5 p-5",className)} {...props}/>}
export function CardTitle({className,...props}:React.HTMLAttributes<HTMLHeadingElement>){return <h2 className={cn("font-semibold tracking-[-.02em]",className)} {...props}/>}
export function CardContent({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn("p-5 pt-0",className)} {...props}/>}
export function Badge({className,variant="default",...props}:React.HTMLAttributes<HTMLSpanElement>&{variant?:"default"|"secondary"}){return <span className={cn("inline-flex items-center rounded-full px-2 py-1 text-xs font-medium",variant==="secondary"?"bg-[var(--accent)] text-[var(--accent-foreground)]":"bg-[var(--primary)] text-[var(--primary-foreground)]",className)} {...props}/>}
export function Progress({value=0}: {value?:number}){return <div role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100} className="h-1.5 overflow-hidden rounded-full bg-[var(--muted)]"><div className="h-full rounded-full bg-[var(--ring)] transition-transform" style={{transform:`translateX(-${100-value}%)`}}/></div>}
export const Input=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(({className,...props},ref)=><input ref={ref} className={cn("h-10 w-full rounded-lg border bg-[var(--background)] px-3 text-sm text-[var(--foreground)] outline-none placeholder:text-[var(--muted-foreground)] focus-visible:border-[var(--ring)] focus-visible:ring-3 focus-visible:ring-[color-mix(in_srgb,var(--ring)_25%,transparent)]",className)} {...props}/>);Input.displayName="Input";
export const Textarea=React.forwardRef<HTMLTextAreaElement,React.TextareaHTMLAttributes<HTMLTextAreaElement>>(({className,...props},ref)=><textarea ref={ref} className={cn("min-h-24 w-full rounded-lg border bg-[var(--background)] px-3 py-2 text-sm text-[var(--foreground)] outline-none placeholder:text-[var(--muted-foreground)] focus-visible:border-[var(--ring)] focus-visible:ring-3 focus-visible:ring-[color-mix(in_srgb,var(--ring)_25%,transparent)]",className)} {...props}/>);Textarea.displayName="Textarea";
export const Select=React.forwardRef<HTMLSelectElement,React.SelectHTMLAttributes<HTMLSelectElement>>(({className,...props},ref)=><select ref={ref} className={cn("h-10 w-full appearance-none rounded-lg border bg-[var(--background)] px-3 text-sm text-[var(--foreground)] outline-none focus-visible:border-[var(--ring)] focus-visible:ring-3 focus-visible:ring-[color-mix(in_srgb,var(--ring)_25%,transparent)]",className)} {...props}/>);Select.displayName="Select";
export const Checkbox=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(({className,...props},ref)=><input ref={ref} type="checkbox" className={cn("size-4 accent-[var(--ring)] focus-visible:outline-2 focus-visible:outline-[var(--ring)] focus-visible:outline-offset-2",className)} {...props}/>);Checkbox.displayName="Checkbox";
export const Switch=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(({className,...props},ref)=><label className={cn("relative inline-flex h-6 w-11 cursor-pointer items-center rounded-full bg-[var(--muted)] transition-colors has-[:checked]:bg-[var(--ring)]",className)}><input ref={ref} type="checkbox" className="peer sr-only" {...props}/><span className="pointer-events-none ml-1 size-4 rounded-full bg-white transition-transform peer-checked:translate-x-5"/></label>);Switch.displayName="Switch";
export function Alert({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div role="status" className={cn("rounded-lg border border-[color-mix(in_srgb,var(--ring)_35%,var(--border))] bg-[color-mix(in_srgb,var(--ring)_10%,transparent)] px-4 py-3 text-sm",className)} {...props}/>}
export function Separator({className,...props}:React.HTMLAttributes<HTMLHRElement>){return <hr className={cn("border-0 border-t border-[var(--border)]",className)} {...props}/>}
export function Skeleton({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div aria-hidden="true" className={cn("animate-pulse rounded-md bg-[var(--muted)]",className)} {...props}/>}
export const Table=React.forwardRef<HTMLTableElement,React.TableHTMLAttributes<HTMLTableElement>>(({className,...props},ref)=><div className="w-full overflow-x-auto"><table ref={ref} className={cn("w-full caption-bottom text-sm",className)} {...props}/></div>);Table.displayName="Table";
export const Avatar=React.forwardRef<React.ElementRef<typeof AvatarPrimitive.Root>,React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Root>>(({className,...props},ref)=><AvatarPrimitive.Root ref={ref} className={cn("relative flex size-9 shrink-0 overflow-hidden rounded-full",className)} {...props}/>);Avatar.displayName="Avatar";
export const AvatarFallback=React.forwardRef<React.ElementRef<typeof AvatarPrimitive.Fallback>,React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Fallback>>(({className,...props},ref)=><AvatarPrimitive.Fallback ref={ref} className={cn("flex size-full items-center justify-center bg-[var(--primary)] text-xs font-semibold text-[var(--primary-foreground)]",className)} {...props}/>);AvatarFallback.displayName="AvatarFallback";
export const DropdownMenu=DropdownPrimitive.Root; export const DropdownMenuTrigger=DropdownPrimitive.Trigger;
export const DropdownMenuContent=React.forwardRef<React.ElementRef<typeof DropdownPrimitive.Content>,React.ComponentPropsWithoutRef<typeof DropdownPrimitive.Content>>(({className,sideOffset=8,...props},ref)=><DropdownPrimitive.Portal><DropdownPrimitive.Content ref={ref} sideOffset={sideOffset} className={cn("z-50 min-w-40 rounded-xl border bg-[var(--popover)] p-1 text-[var(--popover-foreground)] shadow-[0_18px_48px_rgba(0,0,0,.35)]",className)} {...props}/></DropdownPrimitive.Portal>);DropdownMenuContent.displayName="DropdownMenuContent";
export const DropdownMenuItem=React.forwardRef<React.ElementRef<typeof DropdownPrimitive.Item>,React.ComponentPropsWithoutRef<typeof DropdownPrimitive.Item>>(({className,...props},ref)=><DropdownPrimitive.Item ref={ref} className={cn("flex min-h-10 cursor-pointer items-center gap-2 rounded-lg px-3 text-sm outline-none transition-none hover:bg-[var(--accent)] focus:bg-[var(--accent)] data-[highlighted]:bg-[var(--accent)] [&_svg]:size-4",className)} {...props}/>);DropdownMenuItem.displayName="DropdownMenuItem";
export const DropdownMenuLabel=({className,...props}:React.ComponentPropsWithoutRef<typeof DropdownPrimitive.Label>)=><DropdownPrimitive.Label className={cn("px-3 py-2 text-sm font-medium",className)} {...props}/>;
export const DropdownMenuSeparator=({className,...props}:React.ComponentPropsWithoutRef<typeof DropdownPrimitive.Separator>)=><DropdownPrimitive.Separator className={cn("my-1 h-px bg-[var(--border)]",className)} {...props}/>;
export { NomosShell, type ShellApp, type ShellNavItem, type ShellUser } from "./nomos-shell";
export { SectionTabs, type SectionTab } from "./section-tabs";
export { AssistantPanel } from "./assistant-panel";
export { NomosLogo } from "./nomos-logo";
export { NOMOS_APPS } from "./nomos-apps";
export { NomosProductShell, NomosHomeShell } from "./nomos-product-shell";
export { NomosToastViewport, showNomosToast, type NomosToastOptions, type NomosToastTone } from "./nomos-toast";
export { TemplateCatalogue, templatePages, type TemplatePageSlug } from "./template-catalogue-pages";

export { VideoPreview } from "./video-preview";
