"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, Crosshair, Leaf, ShoppingBag, Sun } from "lucide-react";
import { QuestProgress } from "./quest-progress";
import { Button } from "./index";

type Day = { focus:string; improve:string; resources:string };
const empty:Day={focus:"",improve:"",resources:""};
const prefix="nomos.goals.morning.v1.";
const affirmations=[
 "I turn complexity into a clear next step. My experience helps the team move with purpose, even when the path is still taking shape.",
 "I can hold a high standard without carrying every problem alone. Good engineering grows through thoughtful decisions and shared ownership.",
 "I build trust through useful work, honest communication and steady follow-through. I do not need a perfect day to make a meaningful contribution.",
 "I bring curiosity to unfamiliar problems and judgment to difficult choices. I can move quickly while staying deliberate about what matters.",
 "My role is to make the team stronger. A well-asked question, a clear explanation and a small reliable improvement all count as progress.",
 "I can navigate change without losing my footing. I make the best decision with the evidence I have, then learn and adjust.",
 "I have earned the ability to tackle hard things. Today I will protect my attention, share what I know and leave the system a little better.",
];
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function shift(key:string,days:number){const d=new Date(key+"T12:00:00Z");d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function weekStart(key:string){const d=new Date(key+"T12:00:00Z");return shift(key,-((d.getUTCDay()+6)%7));}
function valid(value:unknown):value is Day {return !!value&&typeof value==="object"&&["focus","improve","resources"].every(k=>typeof (value as Record<string,unknown>)[k]==="string");}
const fields=[{key:"focus",title:"Focus",hint:"What deserves your attention?",icon:Crosshair,placeholder:"Start with the thing that matters most…"},{key:"improve",title:"To change / improve",hint:"Small adjustments. Better days.",icon:Leaf,placeholder:"A habit, an approach, something to try differently…"},{key:"resources",title:"To buy / resources needed",hint:"Make room for what will help.",icon:ShoppingBag,placeholder:"Tools, books, people, time — capture it here…"}] as const;

export function MorningManifesto(){
 const [date,setDate]=useState("");const [today,setToday]=useState("");const [notes,setNotes]=useState<Day>(empty);const [status,setStatus]=useState("");const [blocked,setBlocked]=useState(false);const [priorities,setPriorities]=useState<string[]>([]);const [reviewHref,setReviewHref]=useState("/week/");const [prioritySource,setPrioritySource]=useState("");const root=useRef<HTMLDivElement>(null);
 function load(key:string){setDate(key);setBlocked(false);setStatus("");try{const raw=localStorage.getItem(prefix+key);if(raw){const value:unknown=JSON.parse(raw);if(!valid(value))throw Error();setNotes(value);}else setNotes({...empty});}catch{setNotes({...empty});setBlocked(true);setStatus("This day could not be loaded. Reload before writing to protect saved notes.");}}
 useEffect(()=>{const key=localDate();setToday(key);load(key);},[]);
 useEffect(()=>{if(!date)return;function refresh(){try{const records=JSON.parse(localStorage.getItem("nomos.goals.weekly-reviews.v1")||"{}");const monday=weekStart(date);const previous=shift(monday,-7);const previousList=records?.[previous]?.priorities;const currentList=records?.[monday]?.priorities;const usable=(v:unknown):v is string[]=>Array.isArray(v)&&v.length===3&&v.every(x=>typeof x==="string")&&v.some(x=>x.trim());const chosen=usable(previousList)?previous:usable(currentList)?monday:"";setPriorities(chosen?records[chosen].priorities:[]);setPrioritySource(chosen===previous?"From last week’s review":chosen?"From this week’s review":"From your weekly review");setReviewHref(chosen?`/week/?week=${chosen}`:"/week/");}catch{setPriorities([]);setPrioritySource("Weekly priorities couldn’t be loaded");}}refresh();window.addEventListener("focus",refresh);window.addEventListener("storage",refresh);return()=>{window.removeEventListener("focus",refresh);window.removeEventListener("storage",refresh);};},[date]);
 useEffect(()=>{root.current?.querySelectorAll("textarea").forEach(el=>{el.style.height="0px";el.style.height=`${Math.max(el.scrollHeight,34)}px`;});},[notes,date]);
 function update(key:keyof Day,value:string){const previous=notes[key];const addedLine=value.length===previous.length+1&&value.split("\n").length===previous.split("\n").length+1;const lineBreak=addedLine?Array.from({length:value.length},(_,i)=>i).find(i=>value[i]!==previous[i]):-1;const formatted=typeof lineBreak==="number"&&lineBreak>=0&&value[lineBreak]==="\n"?`${value.slice(0,lineBreak+1)}• ${value.slice(lineBreak+1)}`:value;const next={...notes,[key]:formatted};setNotes(next);try{localStorage.setItem(prefix+date,JSON.stringify(next));setStatus("Saved in this browser");}catch{setStatus("Couldn’t save. Keep this page open and copy your notes before leaving.");}}
 if(!date)return <p role="status">Opening your day…</p>;
 const day=new Date(date+"T12:00:00Z");const affirmation=date === "2026-09-10" ? "I trust myself to navigate uncertainty, solve difficult problems and deliver the results expected of a senior engineer." : affirmations[Math.floor(day.getTime()/86400000)%affirmations.length];
 return <section ref={root} className="manifesto-page mx-auto max-w-[1280px] pb-8"><header className="manifesto-toolbar"><div className="flex items-center gap-2 text-sm"><Sun className="size-4 text-[var(--ring)]" aria-hidden="true"/><h2 className="font-medium">Morning Manifesto</h2></div><nav aria-label="Daily navigation" className="flex items-center gap-1"><Button variant="ghost" size="icon" aria-label="Previous day" onClick={()=>load(shift(date,-1))}><ArrowLeft/></Button><label className="sr-only" htmlFor="manifesto-date">Choose day</label><input id="manifesto-date" type="date" value={date} onChange={e=>{if(/^\d{4}-\d{2}-\d{2}$/.test(e.target.value)&&!Number.isNaN(Date.parse(e.target.value)))load(e.target.value);}} className="manifesto-date"/><Button variant="ghost" size="icon" aria-label="Next day" onClick={()=>load(shift(date,1))}><ArrowRight/></Button><Button variant="ghost" disabled={date===today} onClick={()=>load(today)}>Today</Button></nav></header>
 <div className="manifesto-opening"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.18em] text-[var(--muted-foreground)]">Q{Math.floor(day.getUTCMonth()/3)+1} {day.getUTCFullYear()} / MORNING MANIFESTO</p><h3 className="text-4xl font-semibold tracking-[-.045em] sm:text-5xl">{day.toLocaleDateString("en-GB",{weekday:"long",timeZone:"UTC"})}<span className="text-[var(--ring)]">.</span></h3><p className="mt-2 text-lg text-[var(--muted-foreground)]">{day.toLocaleDateString("en-GB",{day:"numeric",month:"long",timeZone:"UTC"})}</p></div><div className="manifesto-affirmation"><p className="mb-3 text-[11px] font-semibold uppercase tracking-[.16em] text-[var(--ring)]">A thought to start with</p><blockquote className="text-xl leading-8 tracking-tight">{affirmation}</blockquote></div></div>
 <div className="manifesto-progress-strip"><QuestProgress quarter={`${day.getUTCFullYear()}-Q${Math.floor(day.getUTCMonth()/3)+1}`} /></div><div className="manifesto-body"><div className="manifesto-pad"><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-[var(--muted-foreground)]">Your scratch pad · write, add, come back</p><span role="status" className="flex items-center gap-1 text-xs text-[var(--muted-foreground)]">{status.startsWith("Saved")&&<Check className="size-3" aria-hidden="true"/>}{status}</span></div>{fields.map(({key,title,hint,icon:Icon,placeholder},i)=><section key={key} className={`manifesto-section manifesto-section-${i}`}><div className="mb-2 flex items-center gap-3"><span className="manifesto-icon"><Icon className="size-4" aria-hidden="true"/></span><label htmlFor={`manifesto-${key}`} className="text-lg font-semibold tracking-tight">{title}</label><span className="ml-auto text-xs text-[var(--muted-foreground)]">0{i+1}</span></div><p id={`manifesto-hint-${key}`} className="mb-3 text-xs text-[var(--muted-foreground)]">{hint}</p><textarea rows={1} id={`manifesto-${key}`} aria-describedby={`manifesto-hint-${key}`} readOnly={blocked} value={notes[key]} onChange={e=>update(key,e.target.value)} placeholder={placeholder} className="manifesto-writing" spellCheck/></section>)}</div>
 <div className="manifesto-sidebar"><aside className="manifesto-week"><div className="mb-6 flex items-center justify-between"><h3 className="text-xs font-semibold uppercase tracking-[.15em]">This week’s top 3</h3><span className="text-[var(--ring)]"><Crosshair className="size-4" aria-hidden="true"/></span></div><ol className="space-y-6">{[0,1,2].map(i=><li key={i} className="flex items-start gap-3"><span className="manifesto-priority-number">{i+1}</span><p className={`text-sm leading-6 ${!priorities[i]?"text-[var(--muted-foreground)]":""}`}>{priorities[i]||"No priority set yet"}</p></li>)}</ol><div className="mt-7 border-t pt-4"><Link href={reviewHref} className="inline-flex min-h-10 items-center gap-2 text-sm font-medium text-[var(--ring)]">Open week<ArrowUpRight className="size-4" aria-hidden="true"/></Link></div></aside></div></div></section>;
}
