// Generated by scripts/sync-app-registry.mjs. Do not edit by hand.
export type NomosGeneratedApp = { slug: string; label: string; localHref: string; productionHref: string; icon: string };
export const generatedNomosApps: NomosGeneratedApp[] = [
  {
    "slug": "admin",
    "label": "Admin",
    "localHref": "http://localhost:3008",
    "productionHref": "https://admin.nomos.codes",
    "icon": "app"
  },
  {
    "slug": "finance",
    "label": "Finance",
    "localHref": "http://localhost:3005",
    "productionHref": "https://finance.nomos.codes",
    "icon": "app"
  },
  {
    "slug": "fitness",
    "label": "Fitness",
    "localHref": "http://localhost:3003",
    "productionHref": "https://fitness.nomos.codes",
    "icon": "fitness"
  },
  {
    "slug": "goals",
    "label": "Goals",
    "localHref": "http://localhost:3006",
    "productionHref": "https://goals.nomos.codes",
    "icon": "app"
  },
  {
    "slug": "home",
    "label": "Home",
    "localHref": "http://localhost:3000",
    "productionHref": "https://nomos.codes",
    "icon": "app"
  },
  {
    "slug": "hustle",
    "label": "Hustle",
    "localHref": "http://localhost:3009",
    "productionHref": "https://hustle.nomos.codes",
    "icon": "app"
  },
  {
    "slug": "template",
    "label": "Template",
    "localHref": "http://localhost:3004",
    "productionHref": "https://template.nomos.codes",
    "icon": "app"
  },
  {
    "slug": "time",
    "label": "Time",
    "localHref": "http://localhost:3007",
    "productionHref": "https://time.nomos.codes",
    "icon": "app"
  }
];
