"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
const areas=["Work","Life","Career","Chores","Creative hobbies","Adventure hobbies"];
export function QuestProgress({quarter,editable=false,questIndex}:{quarter:string;editable?:boolean;questIndex?:number}) {
 const [values,setValues]=useState<(number|null)[]>(Array(6).fill(null));const [message,setMessage]=useState("");const [ready,setReady]=useState(false);
 useEffect(()=>{setReady(false);function load(){try{const raw=localStorage.getItem(`nomos.goals.progress.v1.${quarter}`);const parsed=raw?JSON.parse(raw):Array(6).fill(null);if(!Array.isArray(parsed)||parsed.length!==6||!parsed.every(v=>v===null||(typeof v==="number"&&Number.isFinite(v)&&v>=0&&v<=100)))throw Error();setValues(parsed);setMessage("");setReady(true);}catch{setMessage("Progress could not be loaded.");setReady(false);}}load();window.addEventListener("nomos-progress",load);window.addEventListener("storage",load);window.addEventListener("focus",load);return()=>{window.removeEventListener("nomos-progress",load);window.removeEventListener("storage",load);window.removeEventListener("focus",load);};},[quarter]);
 function update(index:number,value:number){const next=values.map((v,i)=>i===index?value:v);setValues(next);try{localStorage.setItem(`nomos.goals.progress.v1.${quarter}`,JSON.stringify(next));window.dispatchEvent(new Event("nomos-progress"));setMessage("Progress saved.");}catch{setMessage("Couldn’t save progress. Please try again.");}}
 if(questIndex!==undefined)return <div className="mt-4 flex flex-wrap items-center gap-2"><span className="mr-1 text-xs text-[var(--muted-foreground)]">Progress</span>{[0,25,50,75,100].map((value,i)=><button key={value} disabled={!ready} aria-label={`${areas[questIndex]}: ${["Not started","Started","Halfway","Nearly there","Done"][i]}`} aria-pressed={values[questIndex]===value} onClick={()=>update(questIndex,value)} className="quest-step-button">{["Not started","Started","Halfway","Nearly there","Done"][i]}</button>)}{message&&<span role="status" className="text-xs">{message}</span>}</div>;
 return <section className="quest-progress-panel"><div className="mb-1 flex items-center justify-between gap-2"><h3 className="font-semibold">Quest progress</h3><span className="rounded-md bg-[var(--accent)] px-2 py-1 text-xs text-[var(--accent-foreground)]">{quarter.replace("-"," · ")}</span></div><p className="mb-5 text-xs text-[var(--muted-foreground)]">{editable?"Your completion estimates · adjust as you go":"Your completion estimates"}</p><div className="space-y-4">{areas.map((area,i)=><div key={area}><div className="mb-2 flex justify-between gap-2 text-xs"><label htmlFor={editable?`quest-progress-${i}`:undefined}>{area}</label><span className="text-[var(--muted-foreground)]">{values[i]===null?"Not set":`${values[i]}%`}</span></div>{editable?<input id={`quest-progress-${i}`} type="range" min="0" max="100" step="5" disabled={!ready} value={values[i]??0} onChange={e=>update(i,Number(e.target.value))} className="w-full accent-[var(--ring)]"/>:<div role="progressbar" aria-label={`${area} completion estimate`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={values[i]??undefined} aria-valuetext={values[i]===null?"Not set":`${values[i]} percent`} className={`quest-progress-track quest-progress-tone-${Math.floor(i/2)}`}><span style={{width:`${values[i]??0}%`}}/></div>}</div>)}</div>{message&&<p role="status" className="mt-3 text-xs">{message}</p>}{!editable&&<Link href={`/quests/?quarter=${quarter}`} className="mt-5 inline-flex min-h-10 items-center gap-2 text-sm font-medium text-[var(--ring)]">Open quests<ArrowUpRight className="size-4" aria-hidden="true"/></Link>}</section>;
}
