"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Check, ImagePlus, Pencil, Sparkles, Trophy, TrendingUp, Flag, X } from "lucide-react";
import { Button, Input, Textarea } from "./index";

type Review = { priorities:string[]; wins:string[]; improvements:string[]; links:number[]; facts:string[] };
const storeKey="nomos.goals.weekly-reviews.v1";
const areas=["Work","Life","Career","Chores","Side quest · creative","Side quest · adventure"];
const sections=[{key:"priorities",title:"Top 3 priorities",caption:"The plan",icon:Flag},{key:"wins",title:"What went well",caption:"Looking back · 3 wins",icon:Trophy},{key:"improvements",title:"What I’d change",caption:"Looking back · 3 improvements",icon:TrendingUp}] as const;
function monday(date:Date) { const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())); d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d.toISOString().slice(0,10); }
function shift(key:string,days:number) {const d=new Date(key+"T12:00:00Z");d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function iso(key:string) {const d=new Date(key+"T12:00:00Z");d.setUTCDate(d.getUTCDate()+3);const year=d.getUTCFullYear();return {year,week:Math.ceil((((d.getTime()-Date.UTC(year,0,1))/86400000)+1)/7)};}
function weekKey(year:number,week:number) { const jan=new Date(Date.UTC(year,0,4));jan.setUTCDate(jan.getUTCDate()-((jan.getUTCDay()+6)%7)+(week-1)*7);return jan.toISOString().slice(0,10); }
function quarterKey(key:string) {const d=new Date(key+"T12:00:00Z");return `${d.getUTCFullYear()}-Q${Math.floor(d.getUTCMonth()/3)+1}`;}
function empty(facts:string[]):Review {return {priorities:["","",""],wins:["","",""],improvements:["","",""],links:[-1,-1,-1],facts};}
function valid(v:unknown):v is Review {if(!v||typeof v!=="object")return false;const r=v as Review;return [r.priorities,r.wins,r.improvements].every(a=>Array.isArray(a)&&a.length===3&&a.every(x=>typeof x==="string"))&&Array.isArray(r.links)&&r.links.length===3&&r.links.every(n=>Number.isInteger(n)&&n>=-1&&n<6)&&Array.isArray(r.facts)&&r.facts.length===6&&r.facts.every(x=>typeof x==="string");}
export function WeeklyReviews() {
 const [selected,setSelected]=useState("");const [today,setToday]=useState("");const [book,setBook]=useState<Record<string,Review>>({});const [quarters,setQuarters]=useState<Record<string,{facts:string[]}>>({});const [draft,setDraft]=useState<Review|null>(null);const [message,setMessage]=useState("");const [blocked,setBlocked]=useState(false);const [photo,setPhoto]=useState("");const [busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{const key=monday(new Date());const requested=new URLSearchParams(window.location.search).get("week");setSelected(requested&&/^\d{4}-\d{2}-\d{2}$/.test(requested)&&!Number.isNaN(Date.parse(requested))?monday(new Date(requested+"T12:00:00")):key);setToday(key);try {const raw=localStorage.getItem(storeKey);if(raw){const value=JSON.parse(raw);if(!value||typeof value!=="object"||Array.isArray(value)||!Object.entries(value).every(([k,v])=>/^\d{4}-\d{2}-\d{2}$/.test(k)&&valid(v)))throw Error();setBook(value);}const qs=localStorage.getItem("nomos.goals.quarters.v2");if(qs){const value=JSON.parse(qs);if(value&&typeof value==="object")setQuarters(value);}}catch{setMessage("Saved data could not be loaded. Reload before editing to protect existing reviews.");setBlocked(true);}},[]);
 if(!selected)return <p role="status">Loading reviews…</p>;
 const {year,week}=iso(selected);const quarter=quarterKey(selected);const qFacts=quarters[quarter]?.facts;const facts=Array.isArray(qFacts)&&qFacts.length===6&&qFacts.every(v=>typeof v==="string")?qFacts:Array(6).fill("");const content=draft??book[selected]??empty(facts);const range=`${new Date(selected+"T12:00:00Z").toLocaleDateString("en-GB",{day:"numeric",month:"short",timeZone:"UTC"})} – ${new Date(shift(selected,6)+"T12:00:00Z").toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"})}`;
 const records={...book,...(draft?{[selected]:draft}:{})};
 const evidence=areas.map((_,i)=>Object.entries(records).filter(([key])=>quarterKey(key)===quarter&&key<=selected).sort(([a],[b])=>b.localeCompare(a)).flatMap(([key,r])=>r.wins.flatMap((win,n)=>r.links[n]===i&&win.trim()?[{key,win}]:[])));
 const years=Array.from(new Set([year,...Array.from({length:11},(_,i)=>iso(today).year+1-i),...Object.keys(book).map(k=>iso(k).year)])).sort((a,b)=>b-a);
 function move(key:string){setSelected(key);setMessage("");setPhoto("");}
 function edit(){setDraft({...content,priorities:[...content.priorities],wins:[...content.wins],improvements:[...content.improvements],links:[...content.links],facts:[...content.facts]});setMessage("");}
 function save(){if(!draft)return;try{const next={...book,[selected]:draft};localStorage.setItem(storeKey,JSON.stringify(next));setBook(next);setDraft(null);setPhoto("");setMessage("Review saved.");}catch{setMessage("Couldn’t save in this browser. Your edits are still here.");}}
 async function choose(file?:File){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){setMessage("Choose a JPEG, PNG or WebP image under 5 MB.");return;}try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});setDraft({...content,priorities:[...content.priorities],wins:[...content.wins],improvements:[...content.improvements],links:[...content.links],facts:[...content.facts]});setPhoto(data);setMessage("");}catch{setMessage("Couldn’t open this photo. Please try again.");}}
 async function transcribe(){setBusy(true);setMessage("Reading your planner…");try{const response=await fetch("/api/ai/planner-import?appId=goals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image:photo}),signal:AbortSignal.timeout(65000)});const result=await response.json();if(!response.ok)throw Error(result.error||"Couldn’t read the planner.");if(!["priorities","wins","improvements"].every(k=>Array.isArray(result[k])&&result[k].length===3&&result[k].every((v:unknown)=>typeof v==="string")))throw Error("The reader returned an incomplete result. Please try again.");setDraft({...content,priorities:result.priorities,wins:result.wins,improvements:result.improvements,links:[-1,-1,-1]});setMessage(`Transcribed. Check the notes and link each win to a quest before saving. ${typeof result.warning==="string"?result.warning:""}`);}catch(e){setMessage(e instanceof Error?e.message:"Couldn’t read the planner. You can still write your review below.");}finally{setBusy(false);}}
 return <section className="quests-page reviews-page mx-auto max-w-[1400px] pb-6"><header className="mb-7 flex flex-wrap items-center justify-between gap-3"><h2 className="text-3xl font-semibold tracking-tight">Week</h2><span className="text-sm text-[var(--muted-foreground)]">{quarter.replace("-"," · ")}</span></header>
 <nav aria-label="Review week navigation" className="review-navigation"><Button variant="ghost" size="icon" aria-label="Previous week" disabled={!!draft} onClick={()=>move(shift(selected,-7))}><ArrowLeft/></Button><label className="sr-only" htmlFor="review-year">Review year</label><select id="review-year" disabled={!!draft} value={year} onChange={e=>move(weekKey(Number(e.target.value),Math.min(week,iso(`${e.target.value}-12-28`).week)))}>{years.map(y=><option key={y}>{y}</option>)}</select><label className="sr-only" htmlFor="review-week">Week number</label><select id="review-week" disabled={!!draft} value={week} onChange={e=>move(weekKey(year,Number(e.target.value)))}>{Array.from({length:iso(`${year}-12-28`).week},(_,i)=><option key={i} value={i+1}>Week {String(i+1).padStart(2,"0")}{book[weekKey(year,i+1)]?" · Saved":""}</option>)}</select><Button variant="ghost" size="icon" aria-label="Next week" disabled={!!draft} onClick={()=>move(shift(selected,7))}><ArrowRight/></Button><Button variant="ghost" className="ml-auto" disabled={!!draft||selected===today} onClick={()=>move(today)}>This week</Button></nav>
 <div className="my-6 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><CalendarDays className="size-4 text-[var(--muted-foreground)]"/><h3 className="font-semibold">{range}</h3><span className="text-xs text-[var(--muted-foreground)]">{draft?"Editing":book[selected]?"Saved":"Not reviewed"}</span></div><div className="flex gap-2">{draft?<><Button variant="ghost" disabled={busy} onClick={()=>{setDraft(null);setPhoto("");setMessage("");}}>Cancel</Button><Button onClick={save} disabled={busy}><Check/>Save review</Button></>:<Button variant="outline" disabled={blocked} onClick={edit}><Pencil/>{book[selected]?"Edit review":"Write review"}</Button>}</div></div>
 {message&&<p role="status" className="mb-4 rounded-lg border px-4 py-3 text-sm">{message}</p>}
 <section className="review-quest-panel"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h3 className="flex items-center gap-2 font-semibold"><Sparkles className="size-4 text-[var(--ring)]"/>Quarter quests · the story so far</h3><span className="text-xs text-[var(--muted-foreground)]">Generated from linked wins through week {week}</span></div><div className="review-metrics">{areas.map((area,i)=><article key={area} className={`review-metric quest-${i<2?"main":i<4?"maintenance":"side"}`}><div className="flex items-center justify-between gap-2"><h4 className="text-xs font-semibold quest-label">{area}</h4><span className="text-xs text-[var(--muted-foreground)]">0{i+1}</span></div><p className="my-3 text-sm leading-6">{content.facts[i]||"Set this quest in your quarter plan."}</p><p className="mt-auto"><strong className="text-2xl font-semibold">{evidence[i].length}</strong><span className="ml-2 text-xs text-[var(--muted-foreground)]">linked {evidence[i].length===1?"win":"wins"}</span></p><p className="mt-2 text-xs leading-5 text-[var(--muted-foreground)]">{evidence[i][0]?`Latest: ${evidence[i][0].win}`:"No evidence recorded yet"}</p></article>)}</div></section>
 <div className="review-notes-layout"><div className="review-plan-reflect">{sections.map(({key,title,caption,icon:Icon},s)=><section key={key} className={`review-note review-note-${s}`}><header className="mb-5 flex items-center gap-3"><span className="review-section-icon"><Icon className="size-4"/></span><div><h3 className="font-semibold">{title}</h3><p className="text-xs text-[var(--muted-foreground)]">{caption}</p></div></header><ol className="space-y-3">{content[key].map((text,i)=><li key={i} className="flex items-start gap-3"><span className="review-line-number">{i+1}</span><div className="min-w-0 flex-1">{draft?<Textarea aria-label={`${caption} ${i+1}`} disabled={busy} value={text} className="min-h-16" placeholder={key==="priorities"?"What matters most next week?":key==="wins"?"What went well?":"What will you do differently?"} onChange={e=>setDraft({...content,[key]:content[key].map((v,n)=>n===i?e.target.value:v)})}/>:<p className={`review-written-line ${!text?"text-[var(--muted-foreground)]":""}`}>{text||"—"}</p>}{key==="wins"&&(draft?<select aria-label={`Quest for win ${i+1}`} disabled={busy} className="mt-2 max-w-full rounded-md border bg-[var(--background)] p-2 text-xs" value={content.links[i]} onChange={e=>setDraft({...content,links:content.links.map((v,n)=>n===i?Number(e.target.value):v)})}><option value={-1}>Link to a quest…</option>{areas.map((a,n)=><option key={a} value={n}>{a}</option>)}</select>:content.links[i]>=0&&text&&<span className="text-xs text-[var(--muted-foreground)]">{areas[content.links[i]]}</span>)}</div></li>)}</ol></section>)}</div>
 <aside><section className="review-upload"><ImagePlus className="mb-4 size-7 text-[var(--ring)]"/><h3 className="text-lg font-semibold">From paper to here</h3><p className="mb-5 mt-2 text-sm leading-6 text-[var(--muted-foreground)]">Write in your planner. Upload a photo to fill in your priorities, wins and improvements.</p><input ref={input} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" aria-label="Planner photo" disabled={busy||blocked} onChange={e=>{void choose(e.target.files?.[0]);e.target.value="";}}/>{photo?<><img src={photo} alt="Selected planner page" className="mb-3 max-h-64 w-full rounded-lg object-contain"/><div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>void transcribe()}><Sparkles/>{busy?"Reading…":"Read planner"}</Button><Button variant="ghost" size="icon" aria-label="Remove photo" disabled={busy} onClick={()=>setPhoto("")}><X/></Button></div><p className="mt-3 text-xs leading-5 text-[var(--muted-foreground)]">Reading replaces the notes in this unsaved review. Check them before saving.</p></>:<Button variant="outline" disabled={blocked} onClick={()=>input.current?.click()}><ImagePlus/>Upload planner</Button>}<p className="mt-4 text-xs leading-5 text-[var(--muted-foreground)]">JPEG, PNG or WebP · up to 5 MB. The photo is sent to the AI reader when you choose Read planner.</p></section><p className="mt-4 px-2 text-xs leading-5 text-[var(--muted-foreground)]">Quest metrics count linked wins, not overall completion. Reviews are saved in this browser.</p></aside></div></section>;
}
