// Generated by scripts/sync-app-registry.mjs. Do not edit by hand.
export type PlatformApp = { slug: string; name: string; href: string; productionHref: string; icon: string };
export const platformApps: PlatformApp[] = [
  {
    "slug": "admin",
    "name": "Admin",
    "href": "http://localhost:3008",
    "productionHref": "https://admin.nomos.codes",
    "icon": "app"
  },
  {
    "slug": "finance",
    "name": "Finance",
    "href": "http://localhost:3005",
    "productionHref": "https://finance.nomos.codes",
    "icon": "app"
  },
  {
    "slug": "fitness",
    "name": "Fitness",
    "href": "http://localhost:3003",
    "productionHref": "https://fitness.nomos.codes",
    "icon": "fitness"
  },
  {
    "slug": "goals",
    "name": "Goals",
    "href": "http://localhost:3006",
    "productionHref": "https://goals.nomos.codes",
    "icon": "app"
  },
  {
    "slug": "home",
    "name": "Home",
    "href": "http://localhost:3000",
    "productionHref": "https://nomos.codes",
    "icon": "app"
  },
  {
    "slug": "hustle",
    "name": "Hustle",
    "href": "http://localhost:3009",
    "productionHref": "https://hustle.nomos.codes",
    "icon": "app"
  },
  {
    "slug": "template",
    "name": "Template",
    "href": "http://localhost:3004",
    "productionHref": "https://template.nomos.codes",
    "icon": "app"
  },
  {
    "slug": "time",
    "name": "Time",
    "href": "http://localhost:3007",
    "productionHref": "https://time.nomos.codes",
    "icon": "app"
  }
];
