// Generated by scripts/sync-app-registry.mjs. Do not edit by hand.
export type PlatformApp = { slug: string; name: string; href: string; icon: string };
export const platformApps: PlatformApp[] = [
  {
    "slug": "fitness",
    "name": "Fitness",
    "href": "http://localhost:3003",
    "icon": "fitness"
  },
  {
    "slug": "home",
    "name": "Home",
    "href": "http://localhost:3000",
    "icon": "app"
  }
];
