import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const functionsRoot = path.resolve(import.meta.dirname, "..");
const source = path.resolve(functionsRoot, "../db/src/admin.mjs");
const target = path.join(functionsRoot, "src/db.ts");
const implementation = await readFile(source, "utf8");

await writeFile(
  target,
  "// Generated from platform/db/src/admin.mjs. Do not edit this file directly.\n// @ts-nocheck\n" + implementation,
  "utf8",
);
